# Generated by Django 4.1 on 2022-10-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombre_med', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Medico')),
                ('snombre_med', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre del Medico')),
                ('papellido_med', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer apellido Medico')),
                ('sapellido_med', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido Medico')),
                ('dpi_med', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de DPI')),
                ('fecha_nac_med', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('direccion_med', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion del Medico')),
                ('email_med', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Direccion de correo electronico')),
                ('titulo_medico', models.CharField(blank=True, max_length=60, null=True, verbose_name='Titulo')),
                ('telefono_med', models.IntegerField(blank=True, null=True, verbose_name='Numero de telefono Medico')),
                ('sexo_med', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=15, verbose_name='Sexo del Medico')),
                ('religion_med', models.CharField(choices=[('CATOLICO', 'Catolico'), ('EVANGELICO', 'Evangelico'), ('MORMON', 'Mormon')], max_length=20, verbose_name='Religion')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Nombre_Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Clinica')),
                ('direccion_clinica', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion clinica')),
                ('telefono_clinica', models.CharField(blank=True, max_length=13, null=True, verbose_name='Numero de Telefono')),
                ('nit_clinica', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero de nit clinica')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='mision')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='vision')),
            ],
            options={
                'verbose_name': 'Nombre Clinica',
                'verbose_name_plural': 'Nombre Clinicas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombre_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre del paciente')),
                ('snombre_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo nombre del paciente')),
                ('papellido_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Primer apellido paciente')),
                ('sapellido_pac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido paciente')),
                ('dpi_pac', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de DPI')),
                ('fecha_nac_pac', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('direccion_pac', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion del Paciente')),
                ('email_pac', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Direccion de correo electronico')),
                ('telefono_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de telefono paciente')),
                ('sexo_pac', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=15, verbose_name='Sexo del Paciente')),
                ('religion_pac', models.CharField(choices=[('CATOLICO', 'Catolico'), ('EVANGELICO', 'Evangelico'), ('MORMON', 'Mormon')], max_length=20, verbose_name='Religion')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=250, verbose_name='Motivo de la Consulta')),
                ('fecha_consulta', models.DateTimeField()),
                ('diagnostico', models.CharField(max_length=250, verbose_name='Diagnostico')),
                ('observacion', models.TextField(verbose_name='Observacion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
